name: tp1
services:


  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    networks:
      - testing_net
    ports:
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=query_results_ex
      - OUTPUT_EXCHANGE_OF_REVIEWS=scraped_reviews_ex
      - OUTPUT_EXCHANGE_OF_BOOKS=scraped_books_ex
      - OUTPUT_QUEUE_OF_REVIEWS=scraped_reviews_q
      - OUTPUT_QUEUE_OF_BOOKS=scraped_books_q
      - INPUT_QUEUE_OF_QUERY_RESULTS=query_results_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    volumes:
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      server:
        condition: service_started

  # ================================================================


  book_sanitizer:
    container_name: book_sanitizer
    image: book_sanitizer:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=scraped_books_ex
      - OUTPUT_EXCHANGE=sanitized_books_ex
      - INPUT_QUEUE_OF_BOOKS=scraped_books_q
      - OUTPUT_QUEUE_OF_BOOKS=sanitized_books_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  year_preprocessor:
    container_name: year_preprocessor
    image: year_preprocessor:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=sanitized_books_ex
      - OUTPUT_EXCHANGE=preprocessed_books_with_year_ex
      - INPUT_QUEUE_OF_BOOKS=sanitized_books_q
      - OUTPUT_QUEUE_OF_BOOKS_TOWARDS_PREPROC=towards_preprocessor__preprocessed_books_with_year_q
      - OUTPUT_QUEUE_OF_BOOKS_TOWARDS_FILTER=towards_filter__preprocessed_books_with_year_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  decade_preprocessor:
    container_name: decade_preprocessor
    image: decade_preprocessor:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=preprocessed_books_with_year_ex
      - OUTPUT_EXCHANGE=preprocessed_books_with_decade_ex
      - INPUT_QUEUE_OF_BOOKS=towards_preprocessor__preprocessed_books_with_year_q
      - OUTPUT_QUEUE_OF_BOOKS_TOWARDS_EXPANDER=towards_expander__preprocessed_books_with_decade_q
      - OUTPUT_QUEUE_OF_BOOKS_1=preprocessed_books_with_decade_q_1
      - NUM_OF_DYN_OUTPUT_QUEUES=1
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  review_sanitizer:
    container_name: review_sanitizer
    image: review_sanitizer:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=scraped_reviews_ex
      - OUTPUT_EXCHANGE=sanitized_reviews_ex
      - INPUT_QUEUE_OF_REVIEWS=scraped_reviews_q
      - OUTPUT_QUEUE_OF_REVIEWS_1=sanitized_reviews_q_1
      - NUM_OF_DYN_OUTPUT_QUEUES=1
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  merger_1:
    container_name: merger
    image: merger:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE_OF_REVIEWS=sanitized_reviews_ex
      - INPUT_EXCHANGE_OF_BOOKS=preprocessed_books_with_decade_ex
      - OUTPUT_EXCHANGE=merged_reviews_ex
      - INPUT_QUEUE_OF_REVIEWS=sanitized_reviews_q_1
      - INPUT_QUEUE_OF_BOOKS=preprocessed_books_with_decade_q_1
      - OUTPUT_QUEUE_OF_COMPACT_REVIEWS=merged_compact_reviews_q
      - OUTPUT_QUEUE_OF_FULL_REVIEWS=merged_full_reviews_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  # ================================================================


  filter_of_books_by_year:
    container_name: filter_of_books_by_year
    image: filter_of_books_by_year:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=preprocessed_books_with_year_ex
      - OUTPUT_EXCHANGE=books_filtered_by_year_range_ex
      - INPUT_QUEUE_OF_BOOKS=towards_filter__preprocessed_books_with_year_q
      - OUTPUT_QUEUE_OF_BOOKS=books_filtered_by_year_range_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
      
  filter_of_books_by_title:
    container_name: filter_of_books_by_title
    image: filter_of_books_by_title:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=books_filtered_by_year_range_ex
      - OUTPUT_EXCHANGE=books_filtered_by_title_ex
      - INPUT_QUEUE_OF_BOOKS=books_filtered_by_year_range_q
      - OUTPUT_QUEUE_OF_BOOKS=books_filtered_by_title_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  query1_result_generator:
    container_name: query1_result_generator
    image: query1_result_generator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=books_filtered_by_title_ex
      - OUTPUT_EXCHANGE=query_results_ex
      - INPUT_QUEUE_OF_BOOKS=books_filtered_by_title_q
      - OUTPUT_QUEUE_OF_QUERY=query_results_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  # ================================================================


  author_expander:
    container_name: author_expander
    image: author_expander:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=preprocessed_books_with_decade_ex
      - OUTPUT_EXCHANGE=expanded_authors_ex
      - INPUT_QUEUE_OF_BOOKS=towards_expander__preprocessed_books_with_decade_q
      - OUTPUT_QUEUE_OF_AUTHORS_1=expanded_authors_q_1
      - NUM_OF_DYN_OUTPUT_QUEUES=1
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  counter_of_decades_per_author_1:
    container_name: counter_of_decades_per_author_1
    image: counter_of_decades_per_author:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=expanded_authors_ex
      - OUTPUT_EXCHANGE=authors_decades_count_ex
      - INPUT_QUEUE_OF_AUTHORS=expanded_authors_q_1
      - OUTPUT_QUEUE_OF_AUTHORS=authors_decades_count_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  filter_of_authors_by_decade:
    container_name: filter_of_authors_by_decade
    image: filter_of_authors_by_decade:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=authors_decades_count_ex
      - OUTPUT_EXCHANGE=authors_filtered_by_decade_ex
      - INPUT_QUEUE_OF_AUTHORS=authors_decades_count_q
      - OUTPUT_QUEUE_OF_AUTHORS=authors_filtered_by_decade_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
      
  query2_result_generator:
    container_name: query2_result_generator
    image: query2_result_generator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=authors_filtered_by_decade_ex
      - OUTPUT_EXCHANGE=query_results_ex
      - INPUT_QUEUE_OF_AUTHORS=authors_filtered_by_decade_q
      - OUTPUT_QUEUE_OF_QUERY=query_results_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  # ================================================================


  filter_of_compact_reviews_by_decade:
    container_name: filter_of_compact_reviews_by_decade
    image: filter_of_compact_reviews_by_decade:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=merged_reviews_ex
      - OUTPUT_EXCHANGE=compact_reviews_filtered_by_decade_ex
      - INPUT_QUEUE_OF_REVIEWS=merged_compact_reviews_q
      - OUTPUT_QUEUE_OF_REVIEWS_1=compact_reviews_filtered_by_decade_q_1
      - NUM_OF_DYN_OUTPUT_QUEUES=1
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  counter_of_reviews_per_book_1:
    container_name: counter_of_reviews_per_book_1
    image: counter_of_reviews_per_book:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=compact_reviews_filtered_by_decade_ex
      - OUTPUT_EXCHANGE=review_count_per_book_ex
      - INPUT_QUEUE_OF_REVIEWS=compact_reviews_filtered_by_decade_q_1
      - OUTPUT_QUEUE_OF_REVIEWS=review_count_per_book_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  filter_of_books_by_review_count:
    container_name: filter_of_books_by_review_count
    image: filter_of_books_by_review_count:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=review_count_per_book_ex
      - OUTPUT_EXCHANGE=books_filtered_by_review_count_ex
      - INPUT_QUEUE_OF_BOOKS=review_count_per_book_q
      - OUTPUT_QUEUE_OF_BOOKS_TOWARDS_QUERY3=towards_query3__books_filtered_by_review_count_q
      - OUTPUT_QUEUE_OF_BOOKS_TOWARDS_sorter=towards_sorter__books_filtered_by_review_count_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  query3_result_generator:
    container_name: query3_result_generator
    image: query3_result_generator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=books_filtered_by_review_count_ex
      - OUTPUT_EXCHANGE=query_results_ex
      - INPUT_QUEUE_OF_BOOKS=towards_query3__books_filtered_by_review_count_q
      - OUTPUT_QUEUE_OF_QUERY=query_results_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  # ================================================================


  sorter_of_books_by_review_count:
    container_name: sorter_of_books_by_review_count
    image: sorter_of_books_by_review_count:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=books_filtered_by_review_count_ex
      - OUTPUT_EXCHANGE=top_books_by_review_count_ex
      - INPUT_QUEUE_OF_BOOKS=towards_sorter__books_filtered_by_review_count_q
      - OUTPUT_QUEUE_OF_BOOKS=top_books_by_review_count_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  query4_result_generator:
    container_name: query4_result_generator
    image: query4_result_generator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=top_books_by_review_count_ex
      - OUTPUT_EXCHANGE=query_results_ex
      - INPUT_QUEUE_OF_BOOKS=top_books_by_review_count_q
      - OUTPUT_QUEUE_OF_QUERY=query_results_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  # ================================================================


  filter_of_merged_reviews_by_book_genre:
    container_name: filter_of_merged_reviews_by_book_genre
    image: filter_of_merged_reviews_by_book_genre:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=merged_reviews_ex
      - OUTPUT_EXCHANGE=reviews_filtered_by_book_genre_ex
      - INPUT_QUEUE_OF_REVIEWS=merged_full_reviews_q
      - OUTPUT_QUEUE_OF_REVIEWS=reviews_filtered_by_book_genre_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  sentiment_analyzer:
    container_name: sentiment_analyzer
    image: sentiment_analyzer:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=reviews_filtered_by_book_genre_ex
      - OUTPUT_EXCHANGE=sentiment_per_book_ex
      - INPUT_QUEUE_OF_REVIEWS=reviews_filtered_by_book_genre_q
      - OUTPUT_QUEUE_OF_REVIEWS=sentiment_per_book_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  filter_of_books_by_sentiment_quantile:
    container_name: filter_of_books_by_sentiment_quantile
    image: filter_of_books_by_sentiment_quantile:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=sentiment_per_book_ex
      - OUTPUT_EXCHANGE=books_filtered_by_highest_sentiment_ex
      - INPUT_QUEUE_OF_BOOKS=sentiment_per_book_q
      - OUTPUT_QUEUE_OF_BOOKS=books_filtered_by_highest_sentiment_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  query5_result_generator:
    container_name: query5_result_generator
    image: query5_result_generator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_EXCHANGE=books_filtered_by_highest_sentiment_ex
      - OUTPUT_EXCHANGE=query_results_ex
      - INPUT_QUEUE_OF_BOOKS=books_filtered_by_highest_sentiment_q
      - OUTPUT_QUEUE_OF_QUERY=query_results_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
        
  # ================================================================


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

