name: tp1-test
services:

  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    networks:
      - testing_net
    ports:
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - SERVER_PORT=8080
      - INPUT_EXCHANGE=query_results_ex
      - INPUT_QUEUE_OF_QUERY_RESULTS=query_results_q
      - OUTPUT_EXCHANGE_OF_DATA=scraped_data_ex
      - OUTPUT_QUEUE_OF_REVIEWS=scraped_reviews_q
      - OUTPUT_QUEUE_OF_BOOKS=scraped_books_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    volumes:
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - SERVER_PORT=8080
      - SERVER_IP=server
      - REVIEWS_FILE_PATH=/data/books_rating.csv
      - BOOKS_FILE_PATH=/data/books_data.csv
      - BATCH_SIZE=200
    networks:
      - testing_net
    depends_on:
      server:
        condition: service_started



  book_sanitizer:
    container_name: book_sanitizer
    image: book_sanitizer:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=scraped_data_ex
      - OUTPUT_EXCHANGE=sanitized_books_ex
      - INPUT_QUEUE_OF_BOOKS=scraped_books_q
      - OUTPUT_QUEUE_OF_BOOKS=sanitized_books_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  year_preprocessor:
    container_name: year_preprocessor
    image: year_preprocessor:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=sanitized_books_ex
      - OUTPUT_EXCHANGE=preprocessed_books_with_year_ex
      - INPUT_QUEUE_OF_BOOKS=sanitized_books_q
      - OUTPUT_QUEUE_OF_BOOKS_TOWARDS_PREPROC=towards_preprocessor__preprocessed_books_with_year_q
      - OUTPUT_QUEUE_OF_BOOKS_TOWARDS_FILTER=towards_filter__preprocessed_books_with_year_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  decade_preprocessor:
    container_name: decade_preprocessor
    image: decade_preprocessor:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=preprocessed_books_with_year_ex
      - OUTPUT_EXCHANGE=preprocessed_books_with_decade_ex
      - INPUT_QUEUE_OF_BOOKS=towards_preprocessor__preprocessed_books_with_year_q
      - OUTPUT_QUEUE_OF_BOOKS_TOWARDS_EXPANDER=towards_expander__preprocessed_books_with_decade_q
      - OUTPUT_QUEUE_OF_BOOKS_1=preprocessed_books_with_decade_q_1
      - OUTPUT_QUEUE_OF_BOOKS_2=preprocessed_books_with_decade_q_2
      - OUTPUT_QUEUE_OF_BOOKS_3=preprocessed_books_with_decade_q_3
      - NUM_OF_DYN_OUTPUT_QUEUES=3
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  review_sanitizer:
    container_name: review_sanitizer
    image: review_sanitizer:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=scraped_data_ex
      - OUTPUT_EXCHANGE=sanitized_reviews_ex
      - INPUT_QUEUE_OF_REVIEWS=scraped_reviews_q
      - OUTPUT_QUEUE_OF_REVIEWS_1=sanitized_reviews_q_1
      - OUTPUT_QUEUE_OF_REVIEWS_2=sanitized_reviews_q_2
      - OUTPUT_QUEUE_OF_REVIEWS_3=sanitized_reviews_q_3
      - NUM_OF_DYN_OUTPUT_QUEUES=3
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy









  # ================================================================




networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
