name: tp1-test
services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    networks:
      - testing_net
    ports:
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - LOGGING_LEVEL=INFO
      - SERVER_PORT=8080
      - INPUT_EXCHANGE=query_results_ex
      - INPUT_QUEUE_OF_QUERY_RESULTS=query_results_q
      - OUTPUT_EXCHANGE_OF_DATA=scraped_data_ex
      - OUTPUT_QUEUE_OF_REVIEWS=scraped_reviews_q
      - OUTPUT_QUEUE_OF_BOOKS=scraped_books_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    volumes:
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - LOGGING_LEVEL=INFO
      - SERVER_PORT=8080
      - SERVER_IP=server
      - REVIEWS_FILE_PATH=/data/test_rating.csv
      - BOOKS_FILE_PATH=/data/books_data.csv
      - BATCH_SIZE=200
    networks:
      - testing_net
    depends_on:
      server:
        condition: service_started

  book_sanitizer:
    container_name: book_sanitizer
    image: book_sanitizer:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=scraped_data_ex
      - OUTPUT_EXCHANGE=sanitized_books_ex
      - INPUT_QUEUE_OF_BOOKS=scraped_books_q
      - OUTPUT_QUEUE_OF_BOOKS=sanitized_books_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  year_preprocessor:
    container_name: year_preprocessor
    image: year_preprocessor:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=sanitized_books_ex
      - OUTPUT_EXCHANGE=preprocessed_books_with_year_ex
      - INPUT_QUEUE_OF_BOOKS=sanitized_books_q
      - OUTPUT_QUEUE_OF_BOOKS_TOWARDS_PREPROC=towards_preprocessor__preprocessed_books_with_year_q
      - OUTPUT_QUEUE_OF_BOOKS_TOWARDS_FILTER=towards_filter__preprocessed_books_with_year_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  decade_preprocessor:
    container_name: decade_preprocessor
    image: decade_preprocessor:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=preprocessed_books_with_year_ex
      - OUTPUT_EXCHANGE=preprocessed_books_with_decade_ex
      - INPUT_QUEUE_OF_BOOKS=towards_preprocessor__preprocessed_books_with_year_q
      - OUTPUT_QUEUE_OF_BOOKS_TOWARDS_EXPANDER=towards_expander__preprocessed_books_with_decade_q
      - OUTPUT_QUEUE_OF_BOOKS_1=preprocessed_books_with_decade_q_1
      - OUTPUT_QUEUE_OF_BOOKS_2=preprocessed_books_with_decade_q_2
      - OUTPUT_QUEUE_OF_BOOKS_3=preprocessed_books_with_decade_q_3
      - NUM_OF_DYN_OUTPUT_QUEUES=3
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  review_sanitizer:
    container_name: review_sanitizer
    image: review_sanitizer:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=scraped_data_ex
      - OUTPUT_EXCHANGE=sanitized_reviews_ex
      - INPUT_QUEUE_OF_REVIEWS=scraped_reviews_q
      - OUTPUT_QUEUE_OF_REVIEWS_1=sanitized_reviews_q_1
      - OUTPUT_QUEUE_OF_REVIEWS_2=sanitized_reviews_q_2
      - OUTPUT_QUEUE_OF_REVIEWS_3=sanitized_reviews_q_3
      - NUM_OF_DYN_OUTPUT_QUEUES=3
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  merger_1:
    container_name: merger_1
    image: merger:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE_OF_REVIEWS=sanitized_reviews_ex
      - INPUT_EXCHANGE_OF_BOOKS=preprocessed_books_with_decade_ex
      - OUTPUT_EXCHANGE=merged_reviews_ex
      - INPUT_QUEUE_OF_REVIEWS=sanitized_reviews_q_1
      - INPUT_QUEUE_OF_BOOKS=preprocessed_books_with_decade_q_1
      - OUTPUT_QUEUE_OF_COMPACT_REVIEWS=merged_compact_reviews_q
      - OUTPUT_QUEUE_OF_FULL_REVIEWS=merged_full_reviews_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  merger_2:
    container_name: merger_2
    image: merger:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE_OF_REVIEWS=sanitized_reviews_ex
      - INPUT_EXCHANGE_OF_BOOKS=preprocessed_books_with_decade_ex
      - OUTPUT_EXCHANGE=merged_reviews_ex
      - INPUT_QUEUE_OF_REVIEWS=sanitized_reviews_q_2
      - INPUT_QUEUE_OF_BOOKS=preprocessed_books_with_decade_q_2
      - OUTPUT_QUEUE_OF_COMPACT_REVIEWS=merged_compact_reviews_q
      - OUTPUT_QUEUE_OF_FULL_REVIEWS=merged_full_reviews_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  merger_3:
    container_name: merger_3
    image: merger:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE_OF_REVIEWS=sanitized_reviews_ex
      - INPUT_EXCHANGE_OF_BOOKS=preprocessed_books_with_decade_ex
      - OUTPUT_EXCHANGE=merged_reviews_ex
      - INPUT_QUEUE_OF_REVIEWS=sanitized_reviews_q_3
      - INPUT_QUEUE_OF_BOOKS=preprocessed_books_with_decade_q_3
      - OUTPUT_QUEUE_OF_COMPACT_REVIEWS=merged_compact_reviews_q
      - OUTPUT_QUEUE_OF_FULL_REVIEWS=merged_full_reviews_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
  # ================================================================

  filter_of_books_by_year_and_genre:
    container_name: filter_of_books_by_year_and_genre
    image: filter_of_books_by_year_and_genre:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=preprocessed_books_with_year_ex
      - OUTPUT_EXCHANGE=books_filtered_by_year_and_genre_ex
      - INPUT_QUEUE_OF_BOOKS=towards_filter__preprocessed_books_with_year_q
      - OUTPUT_QUEUE_OF_BOOKS=books_filtered_by_year_and_genre_q
      - MIN_YEAR=2000
      - MAX_YEAR=2023
      - GENRE=Computers
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
      
  filter_of_books_by_title:
    container_name: filter_of_books_by_title
    image: filter_of_books_by_title:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=books_filtered_by_year_and_genre_ex
      - OUTPUT_EXCHANGE=books_filtered_by_title_ex
      - INPUT_QUEUE_OF_BOOKS=books_filtered_by_year_and_genre_q
      - OUTPUT_QUEUE_OF_BOOKS=books_filtered_by_title_q
      - TITLE_KEYWORD=distributed
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  query1_result_generator:
    container_name: query1_result_generator
    image: query1_result_generator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=books_filtered_by_title_ex
      - OUTPUT_EXCHANGE=query_results_ex
      - INPUT_QUEUE_OF_BOOKS=books_filtered_by_title_q
      - OUTPUT_QUEUE_OF_QUERY=query_results_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  # ================================================================


  author_expander:
    container_name: author_expander
    image: author_expander:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=preprocessed_books_with_decade_ex
      - OUTPUT_EXCHANGE=expanded_authors_ex
      - INPUT_QUEUE_OF_BOOKS=towards_expander__preprocessed_books_with_decade_q
      - OUTPUT_QUEUE_OF_AUTHORS_1=expanded_authors_q_1
      - OUTPUT_QUEUE_OF_AUTHORS_2=expanded_authors_q_2
      - OUTPUT_QUEUE_OF_AUTHORS_3=expanded_authors_q_3
      - NUM_OF_DYN_OUTPUT_QUEUES=3
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  counter_of_decades_per_author_1:
    container_name: counter_of_decades_per_author_1
    image: counter_of_decades_per_author:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=expanded_authors_ex
      - OUTPUT_EXCHANGE=authors_decades_count_ex
      - INPUT_QUEUE_OF_AUTHORS=expanded_authors_q_1
      - OUTPUT_QUEUE_OF_AUTHORS=authors_decades_count_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  counter_of_decades_per_author_2:
    container_name: counter_of_decades_per_author_2
    image: counter_of_decades_per_author:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=expanded_authors_ex
      - OUTPUT_EXCHANGE=authors_decades_count_ex
      - INPUT_QUEUE_OF_AUTHORS=expanded_authors_q_2
      - OUTPUT_QUEUE_OF_AUTHORS=authors_decades_count_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  counter_of_decades_per_author_3:
    container_name: counter_of_decades_per_author_3
    image: counter_of_decades_per_author:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=expanded_authors_ex
      - OUTPUT_EXCHANGE=authors_decades_count_ex
      - INPUT_QUEUE_OF_AUTHORS=expanded_authors_q_3
      - OUTPUT_QUEUE_OF_AUTHORS=authors_decades_count_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  filter_of_authors_by_decade:
    container_name: filter_of_authors_by_decade
    image: filter_of_authors_by_decade:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=authors_decades_count_ex
      - OUTPUT_EXCHANGE=authors_filtered_by_decade_ex
      - INPUT_QUEUE_OF_AUTHORS=authors_decades_count_q
      - OUTPUT_QUEUE_OF_AUTHORS=authors_filtered_by_decade_q
      - COUNTERS_OF_DECADES_PER_AUTHOR=3
      - MIN_DECADES_TO_FILTER=10
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  query2_result_generator:
    container_name: query2_result_generator
    image: query2_result_generator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=authors_filtered_by_decade_ex
      - OUTPUT_EXCHANGE=query_results_ex
      - INPUT_QUEUE_OF_AUTHORS=authors_filtered_by_decade_q
      - OUTPUT_QUEUE_OF_QUERY=query_results_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  filter_of_compact_reviews_by_decade:
    container_name: filter_of_compact_reviews_by_decade
    image: filter_of_compact_reviews_by_decade:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=1
      - LOGGING_LEVEL=INFO
      - INPUT_EXCHANGE=merged_reviews_ex
      - OUTPUT_EXCHANGE=compact_reviews_filtered_by_decade_ex
      - INPUT_QUEUE_OF_REVIEWS=merged_compact_reviews_q
      - NUM_OF_OUTPUT_QUEUES=3
      - DECADE_TO_FILTER=1990
      - OUTPUT_QUEUE_OF_REVIEWS_1=compact_reviews_filtered_by_decade_q_1
      - OUTPUT_QUEUE_OF_REVIEWS_2=compact_reviews_filtered_by_decade_q_2
      - OUTPUT_QUEUE_OF_REVIEWS_3=compact_reviews_filtered_by_decade_q_3
      - NUM_OF_INPUT_WORKERS=3
      - NUM_OF_DYN_OUTPUT_QUEUES=3
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  # ================================================================

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
