name: tp1-test
services:

  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    networks:
      - testing_net
    ports:
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - SERVER_PORT=8080
      - INPUT_EXCHANGE=query_results_ex
      - INPUT_QUEUE_OF_QUERY_RESULTS=query_results_q
      - OUTPUT_EXCHANGE_OF_DATA=scraped_data_ex
      - OUTPUT_QUEUE_OF_REVIEWS=scraped_reviews_q
      - OUTPUT_QUEUE_OF_BOOKS=scraped_books_q
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    volumes:
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - SERVER_PORT=8080
      - SERVER_IP=server
      - REVIEWS_FILE_PATH=/data/books_rating.csv
      - BOOKS_FILE_PATH=/data/books_data.csv
      - BATCH_SIZE=200
    networks:
      - testing_net
    depends_on:
      server:
        condition: service_started
  # ================================================================




networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
