services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    networks:
      - testing_net
    ports:
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  producer:
    build:
      context: ./producer
      dockerfile: producer.dockerfile
    networks:
      - testing_net
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer1:
    build:
      context: ./consumer
      dockerfile: consumer.dockerfile
    networks:
      - testing_net
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUMER_ID=1
      - LOG_SEVERITY=info
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer2:
    build:
      context: ./consumer
      dockerfile: consumer.dockerfile
    networks:
      - testing_net
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUMER_ID=2
      - LOG_SEVERITY=error
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
